{% set version = "0.3-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nlp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/NLP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/NLP/NLP_{{ version }}.tar.gz
  sha256: c59e8bc6485336bc076e7c37129814fa8ef558ce711fa493510206e6a9254225

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('NLP')"           # [not win]
    - "\"%R%\" -e \"library('NLP')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=NLP
  license: GPL-3.0-only
  summary: Basic classes and methods for Natural Language Processing.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: NLP
# Version: 0.2-0
# Title: Natural Language Processing Infrastructure
# Authors@R: person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org", comment = c(ORCID = "0000-0003-4198-9911"))
# Description: Basic classes and methods for Natural Language Processing.
# License: GPL-3
# Imports: utils
# Depends: R (>= 3.2.0)
# Enhances: udpipe, spacyr, cleanNLP
# NeedsCompilation: no
# Packaged: 2018-10-18 15:27:32 UTC; hornik
# Author: Kurt Hornik [aut, cre] (<https://orcid.org/0000-0003-4198-9911>)
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-10-18 15:58:05 UTC
