# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "G2kfKRornbJfCScqJKo2WY7ArpsHxwhIUyFODT1LgVsrdGSp+1JXwQL+f7rRaDaNLYOJ3TYA9HjBpke7oj+LQD04R4YFTJR0faPp2Tb/jqfilAgy82CQ7vfZRZIlU5wAwDr9fvuDWbwncN9lvo6tab3SUQ79Xezsz8PGNVuilDrWAUfqc7bW6UughJXmo291Eh/ka7e28zZbeoj/Pvp99ZTYKb507I5QdPS0ld6cwy4JgttrRLLwLMCxGJ9n3zAfOxFu1RJnsf/lSwAOrSuO5RwRs7vF4UqVZxC53h6X6NjuHBlAZz8C+DMaoSg85CtOSLdeWAIUbhNrQ1HToUGVEq4ZPahPdAtHg01JROL5Kulz4nJmeK/gJ13xLP8uKybBg3TiMH9TZAkETHtjoAsR6gzMaqkB8mJIkb/SMfm9VKxirUiz7S8bffcXqo/XFMIZoo+N3ZS5I3ra8Q8/R/80Akd/9EDGlFAxPfj+NGrlt1+Vnz+Pa48W0ILG1OuOCuq3CFGmJs1bj6vK8YbslcUhKIpW1QZVUFaefwYlGqmXI8Ndck5xL47sjGvMrYHO7xoJkY6bM+G8Nfu/3r5fvr7CJR9kblptqK3dKV4Cl1I4E8gM6W7ASaEx9lwP4ZHiFDYiHpuvJGufs82WDBKFJ3/gWfBHxr6IFf3+QjP4WSlNKrY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
